apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a9l7up31i-python
  janus-idp.io/tekton: a9l7up31i-python
  backstage.io/kubernetes-id: a9l7up31i-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a9l7up31i-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
